/*********************************************************************
 * File Name: http_print.c
 *
 * Provides callback headers and resolution for user's custom
 * HTTP Application.
 * 
 * This file is automatically generated by the MPFS Utility
 * ALL MODIFICATIONS WILL BE OVERWRITTEN BY THE MPFS GENERATOR
 *
 * Software License Agreement
 *
 * Copyright (C) 2012 Microchip Technology Inc.  All rights
 * reserved.
 * Microchip licenses to you the right to use, modify, copy, and distribute
 * software only embedded on a Microchip microcontroller or digital signal 
 * controller that is integrated into your product or third party product
 * (pursuant to the sublicense terms in the accompanying license agreement)

 * You should refer to the license agreement accompanying this 
 * Software for additional information regarding your rights and 
 * obligations.
 *
 * You should refer to the license agreement accompanying this 
 * Software for additional information regarding your rights and 
 * obligations.
 *
 * THE SOFTWARE AND DOCUMENTATION ARE PROVIDED "AS IS" WITHOUT
 * WARRANTY OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING WITHOUT
 * LIMITATION, ANY WARRANTY OF MERCHANTABILITY, FITNESS FOR A 
 * PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL
 * MICROCHIP BE LIABLE FOR ANY INCIDENTAL, SPECIAL, INDIRECT OR
 * CONSEQUENTIAL DAMAGES, LOST PROFITS OR LOST DATA, COST OF
 * PROCUREMENT OF SUBSTITUTE GOODS, TECHNOLOGY OR SERVICES, ANY CLAIMS
 * BY THIRD PARTIES (INCLUDING BUT NOT LIMITED TO ANY DEFENSE 
 * THEREOF), ANY CLAIMS FOR INDEMNITY OR CONTRIBUTION, OR OTHER 
 * SIMILAR COSTS, WHETHER ASSERTED ON THE BASIS OF CONTRACT, TORT
 * (INCLUDING NEGLIGENCE), BREACH OF WARRANTY, OR OTHERWISE.
 *
 *********************************************************************/

#include "tcpip/tcpip.h"

void TCPIP_HTTP_Print(HTTP_CONN_HANDLE connHandle,uint32_t callbackID);
void TCPIP_HTTP_Print_btn(HTTP_CONN_HANDLE connHandle,uint16_t);
void TCPIP_HTTP_Print_led0(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_led1(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_led2(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_led3(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_led4(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_led5(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_led6(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_led7(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_led8(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_led9(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_led10(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_led11(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_led12(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_led13(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_led14(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_led15(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_led16(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_led17(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_pot0(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_pot1(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_pot2(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_pot3(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_string(HTTP_CONN_HANDLE connHandle,uint16_t);
void TCPIP_HTTP_Print_label(HTTP_CONN_HANDLE connHandle,uint16_t);
void TCPIP_HTTP_Print_coef(HTTP_CONN_HANDLE connHandle,uint16_t);
void TCPIP_HTTP_Print_offs(HTTP_CONN_HANDLE connHandle,uint16_t);
void TCPIP_HTTP_Print_warn(HTTP_CONN_HANDLE connHandle,uint16_t);
void TCPIP_HTTP_Print_successFlag(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_var5(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_var6(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_var1(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_var2(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_var3(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_var4(HTTP_CONN_HANDLE connHandle);

void TCPIP_HTTP_Print(HTTP_CONN_HANDLE connHandle,uint32_t callbackID)
{
    TCP_SOCKET sktHTTP; 
    switch(callbackID)
    {
        case 0x0000000f:
			TCPIP_HTTP_Print_btn(connHandle,0);
			break;
        case 0x00000060:
			TCPIP_HTTP_Print_led0(connHandle);
			break;
        case 0x00000061:
			TCPIP_HTTP_Print_led1(connHandle);
			break;
        case 0x00000062:
			TCPIP_HTTP_Print_led2(connHandle);
			break;
        case 0x00000063:
			TCPIP_HTTP_Print_led3(connHandle);
			break;
        case 0x00000064:
			TCPIP_HTTP_Print_led4(connHandle);
			break;
        case 0x00000065:
			TCPIP_HTTP_Print_led5(connHandle);
			break;
        case 0x00000066:
			TCPIP_HTTP_Print_led6(connHandle);
			break;
        case 0x00000067:
			TCPIP_HTTP_Print_led7(connHandle);
			break;
        case 0x00000068:
			TCPIP_HTTP_Print_led8(connHandle);
			break;
        case 0x00000069:
			TCPIP_HTTP_Print_led9(connHandle);
			break;
        case 0x0000006a:
			TCPIP_HTTP_Print_led10(connHandle);
			break;
        case 0x0000006b:
			TCPIP_HTTP_Print_led11(connHandle);
			break;
        case 0x0000006c:
			TCPIP_HTTP_Print_led12(connHandle);
			break;
        case 0x0000006d:
			TCPIP_HTTP_Print_led13(connHandle);
			break;
        case 0x0000006e:
			TCPIP_HTTP_Print_led14(connHandle);
			break;
        case 0x0000006f:
			TCPIP_HTTP_Print_led15(connHandle);
			break;
        case 0x00000070:
			TCPIP_HTTP_Print_led16(connHandle);
			break;
        case 0x00000071:
			TCPIP_HTTP_Print_led17(connHandle);
			break;
        case 0x00000076:
			TCPIP_HTTP_Print_pot0(connHandle);
			break;
        case 0x00000077:
			TCPIP_HTTP_Print_pot1(connHandle);
			break;
        case 0x00000078:
			TCPIP_HTTP_Print_pot2(connHandle);
			break;
        case 0x00000079:
			TCPIP_HTTP_Print_pot3(connHandle);
			break;
        case 0x0000008e:
			TCPIP_HTTP_Print_string(connHandle,0);
			break;
        case 0x0000008f:
			TCPIP_HTTP_Print_string(connHandle,1);
			break;
        case 0x00000090:
			TCPIP_HTTP_Print_string(connHandle,2);
			break;
        case 0x00000091:
			TCPIP_HTTP_Print_string(connHandle,3);
			break;
        case 0x00000092:
			TCPIP_HTTP_Print_string(connHandle,4);
			break;
        case 0x00000093:
			TCPIP_HTTP_Print_string(connHandle,5);
			break;
        case 0x00000094:
			TCPIP_HTTP_Print_string(connHandle,6);
			break;
        case 0x00000095:
			TCPIP_HTTP_Print_string(connHandle,7);
			break;
        case 0x00000096:
			TCPIP_HTTP_Print_string(connHandle,8);
			break;
        case 0x00000097:
			TCPIP_HTTP_Print_string(connHandle,9);
			break;
        case 0x00000098:
			TCPIP_HTTP_Print_string(connHandle,10);
			break;
        case 0x00000099:
			TCPIP_HTTP_Print_string(connHandle,11);
			break;
        case 0x0000009a:
			TCPIP_HTTP_Print_string(connHandle,12);
			break;
        case 0x0000009b:
			TCPIP_HTTP_Print_string(connHandle,13);
			break;
        case 0x0000009c:
			TCPIP_HTTP_Print_string(connHandle,14);
			break;
        case 0x0000009d:
			TCPIP_HTTP_Print_string(connHandle,15);
			break;
        case 0x0000009e:
			TCPIP_HTTP_Print_string(connHandle,16);
			break;
        case 0x0000009f:
			TCPIP_HTTP_Print_string(connHandle,17);
			break;
        case 0x000000a0:
			TCPIP_HTTP_Print_string(connHandle,18);
			break;
        case 0x000000a1:
			TCPIP_HTTP_Print_string(connHandle,19);
			break;
        case 0x000000a4:
			TCPIP_HTTP_Print_label(connHandle,0);
			break;
        case 0x000000a5:
			TCPIP_HTTP_Print_label(connHandle,1);
			break;
        case 0x000000a6:
			TCPIP_HTTP_Print_label(connHandle,2);
			break;
        case 0x000000a7:
			TCPIP_HTTP_Print_label(connHandle,3);
			break;
        case 0x000000a8:
			TCPIP_HTTP_Print_label(connHandle,4);
			break;
        case 0x000000a9:
			TCPIP_HTTP_Print_label(connHandle,5);
			break;
        case 0x000000aa:
			TCPIP_HTTP_Print_label(connHandle,6);
			break;
        case 0x000000ab:
			TCPIP_HTTP_Print_label(connHandle,7);
			break;
        case 0x000000ac:
			TCPIP_HTTP_Print_coef(connHandle,0);
			break;
        case 0x000000ad:
			TCPIP_HTTP_Print_coef(connHandle,1);
			break;
        case 0x000000ae:
			TCPIP_HTTP_Print_coef(connHandle,2);
			break;
        case 0x000000af:
			TCPIP_HTTP_Print_coef(connHandle,3);
			break;
        case 0x000000b0:
			TCPIP_HTTP_Print_offs(connHandle,0);
			break;
        case 0x000000b1:
			TCPIP_HTTP_Print_offs(connHandle,1);
			break;
        case 0x000000b2:
			TCPIP_HTTP_Print_offs(connHandle,2);
			break;
        case 0x000000b3:
			TCPIP_HTTP_Print_offs(connHandle,3);
			break;
        case 0x000000b4:
			TCPIP_HTTP_Print_warn(connHandle,0);
			break;
        case 0x000000b5:
			TCPIP_HTTP_Print_warn(connHandle,1);
			break;
        case 0x000000b6:
			TCPIP_HTTP_Print_warn(connHandle,2);
			break;
        case 0x000000b7:
			TCPIP_HTTP_Print_warn(connHandle,3);
			break;
        case 0x000000b8:
			TCPIP_HTTP_Print_label(connHandle,8);
			break;
        case 0x000000b9:
			TCPIP_HTTP_Print_label(connHandle,9);
			break;
        case 0x000000ba:
			TCPIP_HTTP_Print_label(connHandle,10);
			break;
        case 0x000000bb:
			TCPIP_HTTP_Print_label(connHandle,11);
			break;
        case 0x000000de:
			TCPIP_HTTP_Print_successFlag(connHandle);
			break;
        case 0x000000df:
			TCPIP_HTTP_Print_var5(connHandle);
			break;
        case 0x000000e0:
			TCPIP_HTTP_Print_var6(connHandle);
			break;
        case 0x000000e1:
			TCPIP_HTTP_Print_var1(connHandle);
			break;
        case 0x000000e2:
			TCPIP_HTTP_Print_var2(connHandle);
			break;
        case 0x000000e3:
			TCPIP_HTTP_Print_var3(connHandle);
			break;
        case 0x000000e4:
			TCPIP_HTTP_Print_var4(connHandle);
			break;
        default:
            // Output notification for undefined values
            sktHTTP = TCPIP_HTTP_CurrentConnectionSocketGet(connHandle);
            TCPIP_TCP_ArrayPut(sktHTTP, (const uint8_t *)"!DEF", 4);
    }
    return;
}

void TCPIP_HTTP_Print_myVariable(HTTP_CONN_HANDLE connHandle)
{
    TCP_SOCKET sktHTTP = TCPIP_HTTP_CurrentConnectionSocketGet(connHandle);
    TCPIP_TCP_Put(sktHTTP, '~');
    return;
}
